apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: rule-devsandbox

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: dev-sandbox, operator: In, values: ["yes"]}